// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VSyFzqAW83GJ7UbM_kGtG-gJuyXpctA',
    appId: '1:142588167260:web:2e8c44f0c95a0d4e0e1299',
    messagingSenderId: '142588167260',
    projectId: 'ksh-a6736',
    authDomain: 'ksh-a6736.firebaseapp.com',
    storageBucket: 'ksh-a6736.appspot.com',
    measurementId: 'G-HPL2BGKP38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4SlpS1edGi7GTcutV0RcKJD24yW1-JcQ',
    appId: '1:142588167260:android:c94ea24179b3346e0e1299',
    messagingSenderId: '142588167260',
    projectId: 'ksh-a6736',
    storageBucket: 'ksh-a6736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuQxZ_1xJlQuLOda7z4n5Zqyyp19gRLpw',
    appId: '1:142588167260:ios:9a9cd80ba58342c10e1299',
    messagingSenderId: '142588167260',
    projectId: 'ksh-a6736',
    storageBucket: 'ksh-a6736.appspot.com',
    iosBundleId: 'com.example.ksh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuQxZ_1xJlQuLOda7z4n5Zqyyp19gRLpw',
    appId: '1:142588167260:ios:9a9cd80ba58342c10e1299',
    messagingSenderId: '142588167260',
    projectId: 'ksh-a6736',
    storageBucket: 'ksh-a6736.appspot.com',
    iosBundleId: 'com.example.ksh',
  );
}
